---
title: "675 Midterm"
author: "Kyle McCarthy"
date: "3/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, message=FALSE, warning=FALSE, include=TRUE, results='hide', cache=TRUE}


library(caret)
library(pscl)
library(plotROC)
library(pROC)
library(sf)
library(tidyverse)
library(knitr)
library(kableExtra)


mapTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 14,colour = "black"),
    plot.subtitle=element_text(face="italic"),
    plot.caption=element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),axis.title = element_blank(),
    axis.text = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2)
  )
}

```


```{r ImportData, message=FALSE, warning=FALSE, include=TRUE, results='hide', cache=TRUE}

sr <- "+proj=utm +zone=12 +ellps=GRS80 +datum=NAD83 +units=m +no_defs" 

Calgary <- st_read("C:/Users/Kyle McCarthy/Documents/CPLN 675/Midterm/midTermProject_Data/CALGIS_CITYBOUND_LIMIT/CALGIS_CITYBOUND_LIMIT.shp")%>% 
  st_transform(crs = sr)

inundation <- st_read("C:/Users/Kyle McCarthy/Documents/CPLN 675/Midterm/inundation.shp")%>% 
  st_transform(crs = sr)%>% 
  mutate(Label = ifelse(gridcode == 0, "No Flooding", "Flooding")) %>% 
  st_make_valid() 

contours <- st_read("C:/Users/Kyle McCarthy/Documents/CPLN 675/Midterm/contours.shp")%>% 
  st_transform(crs = sr)%>% 
  st_make_valid()

imperviousness <- st_read("https://data.calgary.ca/resource/i9mt-qafb.geojson")%>%
  st_transform(crs = sr)

water <- st_read("C:/Users/Kyle McCarthy/Documents/CPLN 675/Midterm/water.shp")%>% 
  st_transform(crs = sr)


fishnet <- 
  st_make_grid(Calgary,
               cellsize = 500) %>%
  st_sf() %>%
  mutate(uniqueID = rownames(.))%>%
  st_transform(crs = sr)



```


```{r ImportData, message=FALSE, warning=FALSE, include=TRUE, results='hide', cache=TRUE}


ggplot()+ 
  geom_sf(data = inundation, aes(fill = Label))+ 
  scale_fill_manual(values = c("#B5F8FE", "#0294A1"))+ 
  labs(title = "Calgary Flood Inundation Map")+
  theme(legend.position = "bottom")+
  mapTheme()


ggplot()+ 
  geom_sf(data = contours, aes(fill = ContourMin))+ 
  labs(title = "Calgary Flood Inundation Map")+
  theme(legend.position = "bottom")+
  mapTheme()


inundation_fishnet <- 
  inundation%>% 
  filter(gridcode == 1)%>% 
  st_intersection(fishnet, inundation)%>% 
  mutate(Area = as.numeric(st_area(.)))%>%
  st_drop_geometry()%>% 
  group_by(uniqueID)%>% 
  summarise(InundationArea = sum(Area))%>% 
  left_join(fishnet, .)%>% 
  mutate(pctInundation = InundationArea / 250000)%>% 
  mutate_all(funs(replace_na(.,0)))%>%
  mutate(Inundated = ifelse(pctInundation > .50, 1, 0))%>%
  mutate(Label = ifelse(Inundated == 1, "Inundated", "Not Inundated"))
  

```


```{r ImportData, message=FALSE, warning=FALSE, include=TRUE, results='hide', cache=TRUE}
ggplot()+ 
  geom_sf(data = inundation_fishnet, aes(fill = Label))+ 
  scale_fill_manual(values = c("#0294A1", "#B5F8FE"))+ 
  labs(title = "Calgary Flood Inundation Map")+
  theme(legend.position = "bottom")+
  mapTheme()


inundation_fishnet <- 
  inundation_fishnet %>% 
  st_centroid()%>% 
  st_make_valid()%>%
  st_join(contours)%>% 
  st_drop_geometry()%>% 
  left_join(fishnet, .)


ggplot(inundation_fishnet, aes(ContourMin))+ 
geom_bar()+ 
  labs(title = "Count of Inundated Gridcells by Elevation")+ 
  xlab("Elevation")+ 
  ylab("Count of Inundated Gridcells")


```


```{r ImportData, message=FALSE, warning=FALSE, include=TRUE, results='hide', cache=TRUE}

# Writing out fishnet as shapefile to perform zonal statistics as table on a euclidean distance raster from Calgary's water features 

# st_write(fishnet, "C:/Users/Kyle McCarthy/Documents/CPLN 675/Midterm/fishnet.shp")

# Reading zonal statistics Shapefile 

inundation_fishnet <- st_read("C:/Users/Kyle McCarthy/Documents/CPLN 675/Midterm/ZonalWater.dbf")%>% 
  dplyr::select(uniqueID, MEAN)%>%
  left_join(inundation_fishnet, .)%>% 
  na.omit()

ggplot() + 
  geom_sf(data = inundation_fishnet, aes(fill = MEAN))+ 
  mapTheme()


ggplot()+ 
  geom_bar(data = inundation_fishnet, aes(x = Label, y = MEAN), stat="identity", fill = "blue")

```

``` {r Imperviousness, message=FALSE, warning=FALSE, include=TRUE, results='hide', cache=TRUE}

Impervious <- st_read("C:/Users/Kyle McCarthy/Documents/GitHub/CPLN-675-Midterm-/Data/Impervious/Imperv_cal.geojson")%>%
  st_transform(crs = sr)

# The Intersection Here Takes a While -- est. 20 min 

inundation_fishnet <- 
  Impervious%>% 
  filter(gen_surface == "Gravel" | gen_surface == "Buildings" | gen_surface == "Pavement" | gen_surface == "Bridge" | gen_surface == "Roads (Pavement)" )%>% 
  st_make_valid()%>%
  st_intersection(fishnet)%>% 
  mutate(Area = as.numeric(st_area(.)))%>% 
  st_drop_geometry()%>% 
  group_by(uniqueID)%>% 
  summarise(Area = sum(Area))%>% 
  mutate(pctImpervious = Area / 250000)%>% 
  left_join(inundation_fishnet, .)%>% 
  mutate(Imperv = ifelse(pctImpervious > 0.50, "Pervious", "Impermeable"))%>% 
  na.omit()

inundation_fishnet<- 
  inundation_fishnet%>% 
  mutate(Imperv = ifelse(pctImpervious > 0.50, "Impervious", "Permeable"))
  


# Group for Graph 

ggplot(inundation_fishnet, aes(x = Imperv)) + 
  geom_bar(aes(fill = Label), position = 'dodge')+ 
  scale_fill_manual(values = c("#E8E6EE", "#08072D"))




```

```{r Building Denisty, message=FALSE, warning=FALSE, include=TRUE, results='hide', cache=TRUE}

inundation_Fish <-st_read("C:/Users/Kyle McCarthy/Documents/GitHub/CPLN-675-Midterm-/Data/Buildings.geojson")%>% 
  st_centroid()%>% 
  st_transform(crs = sr)%>% 
  mutate(BuildingCount = 1) %>%
  dplyr::select(BuildingCount)%>%
  aggregate(., inundation_fishnet, sum)%>% 
  mutate_all(funs(replace_na(.,0)))%>% 
  mutate(uniqueID = rownames(.))%>%
  st_drop_geometry()%>% 
  left_join(inundation_fishnet, .)


BuidlingStats<- 
  inundation_Fish%>% 
  st_drop_geometry()%>%
  na.omit()%>%
  group_by(Label)%>% 
  summarise(BuildingSum = sum(BuildingCount), 
            BuildingCountAverage = mean(BuildingCount))


ggplot()+ 
  geom_bar(data = BuidlingStats, aes(x = Label, y = BuildingCountAverage), stat="identity", fill = "blue")


```



